from __future__ import annotations

import argparse
import ipaddress
import json
import logging
import sys
import threading
from pathlib import Path

from . import __version__, actions, api, notify
from .config import Config
from .detect import analyze, summarize
from .model import Finding, Route, Severity
from .platforms import get_platform
from .util import is_admin, log

SEV_COLOR = {"CRITICAL": "\033[1;41;97m", "HIGH": "\033[1;31m", "MEDIUM": "\033[33m", "LOW": "\033[36m", "INFO": "\033[2m"}


def _setup_logging(verbose: bool, logfile: Path | None = None) -> None:
    handlers: list[logging.Handler] = [logging.StreamHandler(sys.stderr)]
    if logfile:
        try:
            logfile.parent.mkdir(parents=True, exist_ok=True)
            handlers.append(logging.FileHandler(logfile, encoding="utf-8"))
        except OSError:
            pass
    logging.basicConfig(level=logging.DEBUG if verbose else logging.INFO, handlers=handlers,
                        format="%(asctime)s %(levelname)s %(message)s")


def _color(sev: str, text: str) -> str:
    return f"{SEV_COLOR.get(sev, '')}{text}\033[0m" if sys.stdout.isatty() else text


def _simulated_finding(snap) -> Finding:
    vpn = sorted(snap.vpn_interfaces())
    vpn_route = next((r for r in snap.routes if r.iface in vpn and not r.scoped), None) or Route(ipaddress.ip_network("0.0.0.0/0"), vpn[0] if vpn else "tun0")
    phys = next((r.iface for r in snap.routes if r.dest.prefixlen == 0 and r.iface not in vpn), "eth0")
    rogue = Route(ipaddress.ip_network("0.0.0.0/1"), phys, gateway="192.0.2.66", proto="dhcp")
    return Finding(Severity.CRITICAL, "simulated", f"[SIMULATION] Traffic to {rogue.dest} bypasses the VPN via {phys}",
                   "Synthetic finding generated by --simulate to exercise the alert and response flow. Nothing was changed.",
                   iface=phys, route=rogue, vpn_route=vpn_route,
                   evidence=["pushed by DHCP server 192.0.2.66 via option 121 (simulated)"])


def print_report(summary: dict, findings: list[Finding], min_sev: Severity) -> None:
    print(f"TunnelVisionVision {__version__} on {summary['platform']}" + (" (container)" if summary["in_container"] else ""))
    if summary["vpn_active"]:
        print(f"VPN: active on {', '.join(summary['vpn_interfaces'])}")
        for r in summary["vpn_routes"][:6]:
            print(f"     {r}")
    else:
        print("VPN: not detected")
    for l in summary["dhcp_leases"]:
        routes = ", ".join(f"{d} via {g}" for d, g in l["classless_routes"]) or "none"
        print(f"DHCP: {l['iface']} server {l['server'] or '?'}; option 121 routes: {routes}  [{l['source']}]")
    if summary["in_container"]:
        print("Note: running in a container — this checks the container's network namespace. Use host networking to monitor the host.")
    for e in summary["errors"]:
        print(f"Collection warning: {e}")
    print()
    if not findings:
        print("No TunnelVision indicators found.")
        return
    for f in findings:
        print(_color(f.severity.name, f"[{f.severity.name}]") + f" {f.title}")
        print(f"    {f.detail}")
        for e in f.evidence:
            print(f"    - {e}")
    if not any(f.severity >= min_sev for f in findings):
        print(f"\nNothing at or above {min_sev.name}: no alert raised.")


def cmd_check(args, cfg: Config) -> int:
    platform = get_platform(cfg)
    snap = platform.snapshot()
    findings = analyze(snap, cfg, platform)
    if args.simulate:
        platform.dry_run = True
        findings.insert(0, _simulated_finding(snap))
    summary = summarize(snap)
    alertable = [f for f in findings if f.severity >= cfg.notify_min_severity]
    if args.json:
        print(json.dumps({"summary": summary, "findings": [f.to_dict() for f in findings]}, indent=2, default=str))
    else:
        print_report(summary, findings, cfg.notify_min_severity)
    if alertable and (args.interactive or args.simulate):
        alert = {"id": "local", "severity": max(f.severity for f in alertable).name, "findings": [f.to_dict() for f in alertable],
                 "mitigable": any(f.mitigable for f in alertable), "vpn_interfaces": summary["vpn_interfaces"]}
        choice = notify.prompt(alert)
        if choice == "mitigate":
            res = actions.mitigate(platform, snap, alertable)
        elif choice == "disconnect":
            res = actions.disconnect(platform, snap, alertable)
        elif choice == "continue":
            res = actions.acknowledge(platform, snap, alertable, 0)
        else:
            return 1
        notify.show_result(res.to_dict()) if not sys.stdout.isatty() else print("\n" + notify.result_text(res.to_dict()))
    return 1 if alertable else 0


def _start_monitor(cfg: Config, interactive: bool):
    from .daemon import Monitor
    from .sniff import DhcpSniffer

    platform = get_platform(cfg)
    sniffer = None
    if cfg.sniff:
        sniffer = DhcpSniffer()
        sniffer.start()
    monitor = Monitor(cfg, platform, sniffer=sniffer)
    if interactive:
        prompt_lock = threading.Lock()

        def on_alert(alert):
            with prompt_lock:
                notify.notify(notify.TITLE, alert["findings"][0]["title"])
                choice = notify.prompt(alert, timeout=cfg.auto_action_delay if cfg.auto_action != "none" else 0)
                if choice:
                    notify.show_result(monitor.perform(choice, alert["id"], by="console"))

        monitor.on_alert = on_alert
    try:
        token = api.write_token(cfg)
        server = api.serve(cfg, monitor, token.read_text().strip())
        threading.Thread(target=server.serve_forever, daemon=True, name="api").start()
        log.info("API listening on http://%s:%s (token: %s)", cfg.api_host, cfg.api_port, token)
    except Exception as e:
        log.warning("local API disabled: %s", e)
    return monitor


def cmd_daemon(args, cfg: Config) -> int:
    if not is_admin():
        log.warning("not running as root/Administrator: detection works, but mitigate/disconnect will fail")
    log.info("TunnelVisionVision %s daemon starting (poll every %ss, alert at >= %s, auto_action=%s)",
             __version__, cfg.poll_interval, cfg.notify_min_severity.name, cfg.auto_action)
    _start_monitor(cfg, interactive=False).run_forever()
    return 0


def cmd_monitor(args, cfg: Config) -> int:
    log.info("TunnelVisionVision %s monitoring in the foreground (Ctrl-C to stop)", __version__)
    try:
        _start_monitor(cfg, interactive=True).run_forever()
    except KeyboardInterrupt:
        pass
    return 0


def cmd_agent(args, cfg: Config) -> int:
    from .agent import run_agent

    run_agent(cfg)
    return 0


def cmd_status(args, cfg: Config) -> int:
    st = api.call(cfg, "/status")
    if args.json:
        print(json.dumps(st, indent=2, default=str))
        return 0
    s = st.get("summary") or {}
    print(f"daemon {st['version']}; VPN {'active on ' + ', '.join(s.get('vpn_interfaces', [])) if s.get('vpn_active') else 'not detected'}; "
          f"mitigation enforcement {'ON' if st['enforcing_mitigation'] else 'off'}; sniffer: {st.get('sniffer') or 'off'}")
    a = st.get("alert")
    if a:
        print(f"\nALERT {a['id']} [{a['severity']}] status={a['status']}")
        print(notify.alert_text(a))
        if a.get("result"):
            print("\n" + notify.result_text(a["result"]))
    else:
        print("No active alert.")
    return 1 if a and a["status"] == "open" else 0


def cmd_action(args, cfg: Config) -> int:
    res = api.call(cfg, "/action", {"action": args.action, "alert_id": args.alert, "by": "cli"})
    print(notify.result_text(res))
    return 0 if res.get("ok") else 1


def cmd_install(args, cfg: Config) -> int:
    from . import service

    for line in service.install(cfg, agent=not args.no_agent):
        print(line)
    return 0


def cmd_uninstall(args, cfg: Config) -> int:
    from . import service

    for line in service.uninstall():
        print(line)
    return 0


def main(argv=None) -> int:
    p = argparse.ArgumentParser(prog="tvv", description="Detect and respond to TunnelVision (CVE-2024-3661) VPN-decloaking attacks.")
    p.add_argument("--config", type=Path, help="config JSON (default: platform config path or $TVV_CONFIG)")
    p.add_argument("-v", "--verbose", action="store_true")
    p.add_argument("--dry-run", action="store_true", help="print response commands instead of executing them")
    p.add_argument("--version", action="version", version=__version__)
    sub = p.add_subparsers(dest="cmd", required=True)

    c = sub.add_parser("check", help="one-shot scan (exit code 1 if an alert-worthy finding exists)")
    c.add_argument("--json", action="store_true")
    c.add_argument("-i", "--interactive", action="store_true", help="prompt to mitigate/disconnect/continue if something is found")
    c.add_argument("--simulate", action="store_true", help="inject a synthetic attack to test the alert flow (implies --dry-run)")
    c.set_defaults(fn=cmd_check)
    sub.add_parser("monitor", help="continuous monitoring in the foreground with interactive prompts").set_defaults(fn=cmd_monitor)
    sub.add_parser("daemon", help="continuous monitoring as a background service (use with the agent)").set_defaults(fn=cmd_daemon)
    sub.add_parser("agent", help="per-user notifier that shows the daemon's alerts").set_defaults(fn=cmd_agent)
    s = sub.add_parser("status", help="show the daemon's current state")
    s.add_argument("--json", action="store_true")
    s.set_defaults(fn=cmd_status)
    a = sub.add_parser("action", help="answer the current alert (useful on headless hosts/containers)")
    a.add_argument("action", choices=actions.ACTIONS)
    a.add_argument("--alert", help="alert id (default: current alert)")
    a.set_defaults(fn=cmd_action)
    i = sub.add_parser("install-service", help="install the daemon as a system service and the agent at user login")
    i.add_argument("--no-agent", action="store_true")
    i.set_defaults(fn=cmd_install)
    sub.add_parser("uninstall-service").set_defaults(fn=cmd_uninstall)

    args = p.parse_args(argv)
    cfg = Config.load(args.config)
    if args.dry_run:
        cfg.dry_run = True
    _setup_logging(args.verbose, cfg.state_dir / "daemon.log" if args.cmd == "daemon" else None)
    try:
        return args.fn(args, cfg)
    except (RuntimeError, OSError) as e:
        log.error("%s", e)
        return 2
